# Generated by Django 5.2 on 2025-05-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convener', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='club_logos/')),
                ('moto', models.CharField(max_length=255)),
                ('cover_picture', models.ImageField(upload_to='club_covers/')),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
