# Generated by Django 5.2 on 2025-05-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
