# Generated by Django 5.2 on 2025-05-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_clubmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('event', 'Event Details'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic1', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic2', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic3', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic4', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('pic5', models.ImageField(blank=True, null=True, upload_to='club_posts/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.clubmember')),
            ],
        ),
    ]
